{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Import all the packages used"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "import vampnet\n",
    "import data_generator\n",
    "#from keras.models import Model\n",
    "#from keras.layers import Dense, Activation, Flatten, Input, BatchNormalization, concatenate\n",
    "#from keras import optimizers\n",
    "#import tensorflow as tf\n",
    "#from keras.backend import clear_session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "tau = 1\n",
    "# Batch size for Stochastic Gradient descent\n",
    "batch_size = 2048\n",
    "# Which trajectory points percentage is used as training\n",
    "train_ratio = 0.9\n",
    "# How many hidden layers the network has\n",
    "network_depth = 4\n",
    "# Width of every layer\n",
    "layer_width = 20\n",
    "nodes = [layer_width]*network_depth\n",
    "# Learning rate used for the ADAM optimizer\n",
    "learning_rate = 0.0001\n",
    "# How many output states the network has\n",
    "output_size = 5\n",
    "# Iteration over the training set in the fitting process\n",
    "nb_epoch = 300"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-19-1f07876bbbd6>\", line 2, in <module>\n",
      "    vamp = vampnet.VampnetTools(epsilon = epsilon)\n",
      "NameError: name 'vampnet' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: /home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/__init__.py\", line 42, in <module>\n",
      "    from . _api.v2 import audio\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/_api/v2/audio/__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_audio_ops.py\", line 10, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-19-1f07876bbbd6>\", line 2, in <module>\n",
      "    vamp = vampnet.VampnetTools(epsilon = epsilon)\n",
      "NameError: name 'vampnet' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"/home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: /home/htanaka/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'vampnet' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "epsilon = 1e-5\n",
    "vamp = vampnet.VampnetTools(epsilon = epsilon)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Shuffle trajectory and lagged trajectory together\n",
    "length_data = traj_data_points - tau\n",
    "\n",
    "traj_ord= traj_whole[:length_data]\n",
    "traj_ord_lag = traj_whole[tau:length_data+tau]\n",
    "\n",
    "indexes = np.arange(length_data)\n",
    "np.random.shuffle(indexes)\n",
    "\n",
    "\n",
    "\n",
    "traj = traj_ord[indexes]\n",
    "traj_lag = traj_ord_lag[indexes]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare data for tensorflow usage\n",
    "length_train = int(np.floor(length_data * train_ratio))\n",
    "length_vali = length_data - length_train\n",
    "\n",
    "traj_data_train = traj[:length_train]\n",
    "traj_data_train_lag = traj_lag[:length_train]\n",
    "\n",
    "traj_data_valid = traj[length_train:]\n",
    "traj_data_valid_lag = traj_lag[length_train:]\n",
    "\n",
    "#Data used for states ordering\n",
    "X1 = traj_ord[:length_data].astype('float32')\n",
    "X2 = traj_ord_lag[:length_data].astype('float32')\n",
    "\n",
    "# Input of the first network\n",
    "X1_train = traj_data_train.astype('float32')\n",
    "X2_train  = traj_data_train_lag.astype('float32')\n",
    "\n",
    "# Input for validation\n",
    "X1_vali = traj_data_valid.astype('float32')\n",
    "X2_vali = traj_data_valid_lag.astype('float32')\n",
    "\n",
    "# Needs a Y-train set which we dont have.\n",
    "Y_train = np.zeros((length_train,2*output_size)).astype('float32')\n",
    "Y_vali = np.zeros((length_vali,2*output_size)).astype('float32')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "if 'model' in globals():\n",
    "    del model\n",
    "    clear_session()\n",
    "# Build the model\n",
    "Data_X = Input(shape = (input_size,))\n",
    "Data_Y = Input(shape = (input_size,))\n",
    "\n",
    "# A batch normalization layer improves convergence speed\n",
    "#     bn_layer = BatchNormalization()\n",
    "bn_layer = Activation('linear')\n",
    "\n",
    "# Instance layers and assign them to the two lobes of the network\n",
    "dense_layers = [Dense(node, activation = 'relu',)\n",
    "                for node in nodes]\n",
    "\n",
    "lx_branch = bn_layer(Data_X)\n",
    "rx_branch = bn_layer(Data_Y)\n",
    "\n",
    "for i, layer in enumerate(dense_layers):\n",
    "\n",
    "    lx_branch = dense_layers[i](lx_branch)\n",
    "    rx_branch = dense_layers[i](rx_branch)\n",
    "\n",
    "\n",
    "# Add a softmax output layer.\n",
    "# Should be replaced with a linear activation layer if\n",
    "# the outputs of the network cannot be interpreted as states\n",
    "softmax = Dense(output_size, activation='softmax')\n",
    "\n",
    "lx_branch = softmax(lx_branch)\n",
    "rx_branch = softmax(rx_branch)\n",
    "\n",
    "# Merge both networks to train both at the same time\n",
    "merged = concatenate([lx_branch, rx_branch])\n",
    "\n",
    "# Initialize the model and the optimizer, and compile it with\n",
    "# the loss and metric functions from the VAMPnets package\n",
    "model = Model(inputs = [Data_X, Data_Y], outputs = merged)\n",
    "#     model.summary()\n",
    "# Compile it with our own loss-function\n",
    "adam = optimizers.adam(lr = learning_rate)\n",
    "\n",
    "\n",
    "# Pretraining with VAMP with 'symmetrized' matrices yields a bad approximation of the \n",
    "# eigenvectors per se, but improves the 'readability' of the states identified by VAMP-2\n",
    "# which would otherwise be difficult to interprete.\n",
    "\n",
    "\n",
    "# IMPORTANT: the function vamp.loss_VAMP2_autograd can only be used with tensorflow 1.6 or more recent.\n",
    "# For older versions of TF, use the function vamp.loss_VAMP2\n",
    "\n",
    "losses = [\n",
    "    vamp._loss_VAMP_sym,\n",
    "    vamp.loss_VAMP2,\n",
    "]\n",
    "\n",
    "valid_metric = np.zeros((len(losses), nb_epoch))\n",
    "train_metric = np.zeros((len(losses), nb_epoch))\n",
    "\n",
    "for l_index, loss in enumerate(losses):\n",
    "    \n",
    "    model.compile(optimizer = 'adam', loss = loss, metrics = [vamp.metric_VAMP])\n",
    "    \n",
    "    hist = model.fit([X1_train, X2_train], Y_train ,batch_size=batch_size, epochs=nb_epoch, verbose=0,\n",
    "                     validation_data=([X1_vali, X2_vali], Y_vali))\n",
    "    \n",
    "    temp = model.predict([traj_ord, traj_ord_lag], batch_size=np.shape(X1_vali)[0])\n",
    "    \n",
    "    x_a = temp[:,:output_size]\n",
    "\n",
    "\n",
    "    X_Validation = np.squeeze(traj_ord)\n",
    "    for i in range(output_size):\n",
    "        plt.scatter(X_Validation, x_a[:,i], label= 'state '+str(i))\n",
    "    plt.title('State probabilities')\n",
    "    plt.legend()\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    states_prob_meanfree = x_a  - np.mean(x_a, axis=0)\n",
    "    tau_msm = 5\n",
    "    K_smt = vamp.estimate_koopman_op(states_prob_meanfree, tau_msm)\n",
    "\n",
    "    K_eigvals, K_eigvec = np.linalg.eig(np.real(K_smt))\n",
    "\n",
    "    index = np.argmax(np.real(K_eigvals))\n",
    "    real_eigfunc = states_prob_meanfree @ np.real(K_eigvec[:,index])\n",
    "\n",
    "    plt.scatter(X_Validation, real_eigfunc)\n",
    "    plt.title('Eigenvector')\n",
    "    plt.show()\n",
    "\n",
    "    valid_metric[l_index] = np.array(hist.history['val_metric_VAMP'])\n",
    "    train_metric[l_index] = np.array(hist.history['metric_VAMP'])\n",
    "\n",
    "valid_metric = np.reshape(valid_metric, (-1))\n",
    "train_metric = np.reshape(train_metric, (-1))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Training result visualization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.plot(train_metric, label = 'Training')\n",
    "plt.legend()\n",
    "plt.plot(valid_metric, label = 'Validation')\n",
    "plt.legend()\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Transform the input trajectory using the network"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "states_prob = model.predict([traj_ord, traj_ord_lag])[:, :output_size]\n",
    "\n",
    "# Order the output states based on their population\n",
    "coor_pred = np.argmax(states_prob, axis = 1)\n",
    "indexes = [np.where(coor_pred == np.multiply(np.ones_like(coor_pred), n)) for n in range(output_size)]\n",
    "states_num = [len(i[0]) for i in indexes]\n",
    "states_order = np.argsort(states_num).astype('int')[::-1]\n",
    "\n",
    "pred_ord = states_prob[:,states_order]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Visualize the population of the states"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def print_states_pie_chart():\n",
    "    coors = []\n",
    "    maxi = np.max(pred_ord, axis= 1)\n",
    "\n",
    "    for i in range(output_size):\n",
    "        coors.append(len(np.where(pred_ord[:,i] == maxi)[0]))\n",
    "        \n",
    "    fig1, ax1 = plt.subplots()\n",
    "    ax1.pie(np.array(coors), autopct='%1.2f%%', startangle=90)\n",
    "    ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.\n",
    "    print('States population: '+str(np.array(coors)/len(maxi)*100)+'%')\n",
    "    plt.show()\n",
    "\n",
    "print_states_pie_chart()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Estimate the implied timescales"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_tau = 15\n",
    "lag = np.arange(1, max_tau, 1)\n",
    "its = vamp.get_its(pred_ord, lag)\n",
    "vamp.plot_its(its, lag)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Chapman-Kolmogorov test for the estimated koopman operator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "steps = 16\n",
    "tau_msm = 1\n",
    "predicted, estimated = vamp.get_ck_test(pred_ord, steps, tau_msm)\n",
    "vamp.plot_ck_test(predicted, estimated, output_size, steps, tau_msm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
